routes/web.php
<?php
include_once 'web_builder.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::pattern('slug', '[a-z0-9- _]+');

Route::group(['prefix' => 'admin', 'namespace'=>'Admin'], function () {

    # Error pages should be shown without requiring login
    Route::get('404', function () {
        return view('admin/404');
    });
    Route::get('500', function () {
        return view('admin/500');
    });
    # Lock screen
    Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
    Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');

    # All basic routes defined here
    Route::get('login', 'AuthController@getSignin')->name('login');
    Route::get('signin', 'AuthController@getSignin')->name('signin');
    Route::post('signin', 'AuthController@postSignin')->name('postSignin');
    Route::post('signup', 'AuthController@postSignup')->name('admin.signup');
    Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password');
    
    Route::get('login2', function () {
        return view('admin/login2');
    });


    # Forgot Password Confirmation
    Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
    Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

    # Logout
    Route::get('logout', 'AuthController@getLogout')->name('logout');

    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
});


Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
# currently used routes
     # Activity log
    Route::get('activity-log', 'JoshController@activityLogData')->name('activity_log.data');
     # Dashboard / Index
    Route::get('/', 'JoshController@showHome')->name('dashboard');
});



Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {


    # Role Management
    Route::group(['prefix' => 'roles'], function () {
        Route::get('{role}/delete', 'RolesController@destroy')->name('roles.delete');
        Route::get('{role}/confirm-delete', 'RolesController@getModalDelete')->name('roles.confirm-delete');
        Route::get('{role}/restore', 'RolesController@getRestore')->name('roles.restore');
    });
    Route::resource('roles', 'RolesController');

    # Students Management
    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
//        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
        Route::post('passwordreset', 'UsersController@passwordreset')->name('passwordreset');

       //import and export excel
        Route::get('export', 'ExcelController@userExport')->name('users.export');
        Route::post('import', 'ExcelController@import')->name('import');

    });
    Route::resource('users', 'UsersController');

    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');


    # Group Management
    Route::group(['prefix' => 'groups'], function () {
        Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
        Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
        Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
    });
    Route::resource('groups', 'GroupsController');

    /*routes for blog*/
    Route::group(['prefix' => 'blog'], function () {
        Route::get('{blog}/delete', 'BlogController@destroy')->name('blog.delete');
        Route::get('{blog}/confirm-delete', 'BlogController@getModalDelete')->name('blog.confirm-delete');
        Route::get('{blog}/restore', 'BlogController@restore')->name('blog.restore');
        Route::post('{blog}/storecomment', 'BlogController@storeComment')->name('storeComment');
    });
    Route::resource('blog', 'BlogController');

    /*routes for blog category*/
    Route::group(['prefix' => 'blogcategory'], function () {
        Route::get('{blogCategory}/delete', 'BlogCategoryController@destroy')->name('blogcategory.delete');
        Route::get('{blogCategory}/confirm-delete', 'BlogCategoryController@getModalDelete')->name('blogcategory.confirm-delete');
        Route::get('{blogCategory}/restore', 'BlogCategoryController@getRestore')->name('blogcategory.restore');
    });
    Route::resource('blogcategory', 'BlogCategoryController');

     # Class Management
    Route::group(['prefix' => 'classes'], function () {
        Route::get('{class}/delete', 'ClassController@destroy')->name('classes.delete');
        Route::get('{class}/confirm-delete', 'ClassController@getModalDelete')->name('classes.confirm-delete');
        Route::get('{class}/restore', 'ClassController@getRestore')->name('classes.restore');
    });
    Route::resource('classes', 'ClassController');

     # Acadamic Year Management
    Route::group(['prefix' => 'acadamic_years'], function () {
        Route::get('{acadamic_years}/delete', 'AcadamicYearController@destroy')->name('acadamic_years.delete');
        Route::get('{acadamic_years}/confirm-delete', 'AcadamicYearController@getModalDelete')->name('acadamic_years.confirm-delete');
    });
    Route::resource('acadamic_years', 'AcadamicYearController');

    # Year Management
    Route::group(['prefix' => 'years'], function () {
        Route::get('{year}/delete', 'YearController@destroy')->name('year.delete');
        Route::get('{year}/confirm-delete', 'YearController@getModalDelete')->name('year.confirm-delete');
        Route::get('{year}/restore', 'YearController@getRestore')->name('year.restore');
    });
    Route::resource('years', 'YearController');


    # Quarter Management
    Route::group(['prefix' => 'quarter'], function () {
        Route::get('{quarter}/delete', 'QuarterController@destroy')->name('quarter.delete');
        Route::get('{quarter}/confirm-delete', 'QuarterController@getModalDelete')->name('quarter.confirm-delete');
        Route::get('{class}/restore', 'QuarterController@getRestore')->name('quarter.restore');
    });
    Route::resource('quarter', 'QuarterController');

    # Courses
    Route::group(['prefix' => 'courses'], function () {
        Route::get('{course}/delete', 'CourseController@destroy')->name('course.delete');
        Route::get('{course}/confirm-delete', 'CourseController@getModalDelete')->name('course.confirm-delete');
        Route::get('{course}/restore', 'CourseController@getRestore')->name('course.restore');
    });
    Route::resource('courses', 'CourseController');



     # Course Management
    Route::group(['prefix' => 'course-management'], function () {
        Route::get('{id}/delete', 'CourseManagementController@destroy')->name('course-management.delete');
        Route::get('{id}/confirm-delete', 'CourseManagementController@getModalDelete')->name('course-management.confirm-delete');
        Route::get('{course-management}/restore', 'CourseManagementController@getRestore')->name('course-management.restore');
    });
    Route::resource('course-management', 'CourseManagementController');
   



     # Professor Management
    Route::group(['prefix' => 'professor'], function () {
        Route::get('{professor}/delete', 'ProfessorController@destroy')->name('professor.delete');
        Route::get('{professor}/confirm-delete', 'ProfessorController@getModalDelete')->name('professor.confirm-delete');
        Route::get('{professor}/restore', 'ProfessorController@getRestore')->name('professor.restore');
    });
    Route::resource('professor', 'ProfessorController');


     # free download files Management
    Route::group(['prefix' => 'freedownload'], function () {
        Route::get('{freedownload}/delete', 'FreeDownloadController@destroy')->name('freedownload.delete');
        Route::get('{freedownload}/confirm-delete', 'FreeDownloadController@getModalDelete')->name('freedownload.confirm-delete');
        Route::get('{freedownload}/restore', 'FreeDownloadController@getRestore')->name('freedownload.restore');
    });
    Route::resource('freedownload', 'FreeDownloadController');


     # about Management
    Route::group(['prefix' => 'about'], function () {
        Route::get('{about}/delete', 'AboutController@destroy')->name('about.delete');
        Route::get('{about}/confirm-delete', 'AboutController@getModalDelete')->name('about.confirm-delete');
        Route::get('{about}/restore', 'AboutController@getRestore')->name('about.restore');
    });
    Route::resource('about', 'AboutController');

     # Exam Management
    Route::group(['prefix' => 'exam'], function () {
        Route::get('{exam}/delete', 'ExamController@destroy')->name('exam.delete');
        Route::get('{exam}/confirm-delete', 'ExamController@getModalDelete')->name('exam.confirm-delete');
        Route::get('{exam}/restore', 'ExamController@getRestore')->name('exam.restore');
    });
    Route::resource('exam', 'ExamController');

    # ExamResult Management
    Route::group(['prefix' => 'exam-result'], function () {

resources/views/admin/500.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>500 Internal Error | naypyitawmbac.com </title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- global level js -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- end of global js-->
    <!-- page level styles-->
    <link href="{{ asset('assets/css/pages/500.css') }}" rel="stylesheet" type="text/css"/>
    <!-- end of page level styles-->
</head>
<body>
    <div class="container-fluid">
        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-offset-1 col-xs-10 middle">
            <div class="error-container">
                <div class="error-main">
                    <h1> <i class="livicon" data-name="warning" data-s="100" data-c="#ffbc60" data-hc="#ffbc60" data-eventtype="click" data-iteration="15" data-duration="2000"></i>
                        500
                    </h1>
                    <h3>
                        Thats an error.
                        <br>There was an error. Please Try again later. Thats all we know
                    </h3>
                        <a href="{{ route('admin.dashboard') }}" class="btn btn-warning">Home</a>
                    <br>
                </div>
            </div>
        </div>
    </div>
    <!-- global js -->
    <script src="{{ asset('assets/js/jquery-1.11.1.min.js') }}" type="text/javascript"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
    <!--livicons-->
    <script src="{{ asset('assets/js/raphael-min.js') }}"></script>
    <script src="{{ asset('assets/js/livicons-1.4.min.js') }}"></script>
    <script src="{{ asset('assets/js/holder.js') }}"></script>
    <!-- end of global js -->
    <!-- begining of page level js-->
    <script>
    $("document").ready(function() {
        setTimeout(function() {
            $(".livicon").trigger('click');
        }, 10);
    });
    // code for aligning center
    $(document).ready(function() {
        var x = $(window).height();
        var y = $(".middle").height();

        x = x - y;
        x = x / 2;
        $(".middle").css("padding-top", x);
    });
    </script>
    <!-- end of page level js-->
</body>
</html>

resources/views/admin/activity_log.blade.php
@extends('admin/layouts/default')

{{-- Page title --}}
@section('title')
    Activity log
    @parent
@stop

{{-- page level styles --}}
@section('header_styles')
    <link rel="stylesheet" type="text/css"
          href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}"/>
    <link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css"/>
@stop


{{-- Page content --}}
@section('content')
    <section class="content-header">
        <h1>Activity log</h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('admin.dashboard') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
            </li>

            <li class="active">Activity log</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content paddingleft_right15">
        <div class="row">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="livicon" data-name="user" data-size="16" data-loop="true"
                                               data-c="#fff" data-hc="white"></i>
                        Activity Log
                    </h4>
                </div>
                <br/>
                <?php 
                    $keyword = isset($_GET['keyword'])?$_GET['keyword']:'';
                ?>
                <form action="{{ url('/admin/activity-log') }}" method="GET">
                    <div class="row">
                        <div class="col-md-3"  style="float: right;">
                            <input type="text" class="form-control" name="keyword" placeholder="Search .." value="{{ $keyword }}">
                        </div>
                    </div>
                </form>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-bordered " id="table">
                            <thead>
                            <tr class="filters">
                                <th>Name</th>
                                <th>Description</th>
                                <th>created time</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($activities as $activity)
                                <tr>
                                    <td>{!! $activity->log_name !!}</td>
                                    <td>{!! $activity->description !!}</td>
                                    <td>{!! $activity->created_at !!}</td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                        {!! $activities->render() !!}
                    </div>
                </div>
            </div>
        </div>    <!-- row-->
    </section>
@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable({
                "order": [[3, "desc"]]
            });
        });
    </script>
@stop

resources/views/admin/deleted_users.blade.php
@extends('admin/layouts/default')

{{-- Page title --}}
@section('title')
Deleted users
@parent
@stop

{{-- page level styles --}}
@section('header_styles')

    <link rel="stylesheet" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}" />
    <link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
    <!-- end page css -->
@stop

{{-- Page content --}}
@section('content')

<section class="content-header">
                <h1>Deleted users</h1>
                <ol class="breadcrumb">
                    <li>
                        <a href="{{ route('admin.dashboard') }}">
                            <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                            Dashboard
                        </a>
                    </li>
                    <li><a href="#"> Users</a></li>
                    <li class="active">Deleted users</li>
                </ol>
            </section>
            <!-- Main content -->
         <section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <i class="livicon" data-name="users-remove" data-size="18" data-c="#ffffff" data-hc="#ffffff"></i>
                    Deleted Users List
                </h4>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                <table class="table table-bordered" id="table">
                    <thead>
                    <tr class="filters">
                        <th>Name</th>
                        <th>E-mail</th>
                        <th>Created At</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <td>{!! $user->username !!}</td>
                            <td>{!! $user->email !!}</td>
                            <td>{!! $user->created_at->diffForHumans() !!}</td>
                            <td>
                                <a href="{{ route('admin.restore.user', $user->id) }}"><i class="livicon" data-name="user-flag" data-c="#6CC66C" data-hc="#6CC66C" data-size="18"></i></a>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</section>

        
    @stop

{{-- page level scripts --}}
@section("footer_scripts")
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}" ></script>
    <script>
        $(document).ready(function() {
            $('#table').DataTable();
        });
    </script>
@stop

resources/views/admin/googlemaps.blade.php
@extends('admin/layouts/default')

{{-- Page title --}}
@section('title')
    Google Maps
    @parent
@stop

{{-- page level styles --}}
@section('header_styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/gmaps/css/examples.css') }}"/>
    <link href="{{ asset('assets/css/pages/googlemaps_custom.css') }}" rel="stylesheet">
@stop

{{-- Page content --}}
@section('content')

    <section class="content-header">
        <h1>Google Maps</h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('admin.dashboard') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
            </li>
            <li><a href="#">Maps</a></li>
            <li class="active">Google Maps</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-lg-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="panel-title">Basic</h4>
                                <span class="pull-right">
                                    <i class="glyphicon glyphicon-chevron-up showhide clickable"></i>
                                    <i class="glyphicon glyphicon-remove removepanel clickable"></i>
                                </span>
                    </div>
                    <div class="panel-body" style="padding:10px !important;">
                        <div id="gmap-top" class="gmap"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <!-- Basic charts strats here-->
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h4 class="panel-title">Terrain</h4>
                                <span class="pull-right">
                                    <i class="glyphicon glyphicon-chevron-up showhide clickable"></i>
                                    <i class="glyphicon glyphicon-remove removepanel clickable"></i>
                                </span>
                    </div>
                    <div class="panel-body" style="padding:10px !important;">
                        <div id="gmap-terrain" class="gmap"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-lg-6">
                <!-- Basic charts strats here-->
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h4 class="panel-title">Satellite</h4>
                                <span class="pull-right">
                                    <i class="glyphicon glyphicon-chevron-up showhide clickable"></i>
                                    <i class="glyphicon glyphicon-remove removepanel clickable"></i>
                                </span>
                    </div>
                    <div class="panel-body" style="padding:10px !important;">
                        <div id="gmap-satellite" class="gmap"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <!-- Basic charts strats here-->
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <h4 class="panel-title">Markers</h4>
                                <span class="pull-right">
                                    <i class="glyphicon glyphicon-chevron-up showhide clickable"></i>
                                    <i class="glyphicon glyphicon-remove removepanel clickable"></i>
                                </span>
                    </div>
                    <div class="panel-body" style="padding:10px !important;">
                        <div id="gmap-markers" class="gmap"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-lg-6">
                <!-- Basic charts strats here-->
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h4 class="panel-title">Styled Maps</h4>
                                <span class="pull-right">
                                    <i class="glyphicon glyphicon-chevron-up showhide clickable"></i>
                                    <i class="glyphicon glyphicon-remove removepanel clickable"></i>
                                </span>
                    </div>
                    <div class="panel-body" style="padding:10px !important;">
                        <div id="gmap-styled" class="gmap"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <!-- Basic charts strats here-->
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h4 class="panel-title">Map Types</h4>
                                <span class="pull-right">
                                    <i class="glyphicon glyphicon-chevron-up showhide clickable"></i>
                                    <i class="glyphicon glyphicon-remove removepanel clickable"></i>
                                </span>
                    </div>
                    <div class="panel-body" style="padding:10px !important;">
                        <div id="gmap-types" class="gmap"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- row -->
    </section>

@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/js/pages/maps_api.js') }}"></script>
    <script type="text/javascript"
            src="http://maps.google.com/maps/api/js?key=AIzaSyADWjiTRjsycXf3Lo0ahdc7dDxcQb475qw&libraries=places"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/gmaps/js/gmaps.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/custommaps.js') }}"></script>

@stop

resources/views/admin/lockscreen.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Lock Screen | Josh Admin Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="_token" content="{{ csrf_token() }}">
    <!-- global level css -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" />
    <!-- end of global level css -->
    <!-- page level css -->
    <link href="{{ asset('assets/css/pages/lockscreen.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('assets/vendors/fort_js/css/fort.css') }}" />
    <!-- end of page level css -->
</head>

<body>
<div class="top">
    <div class="colors"></div>
</div>
<div class="container">
    <div class="login-container">
        <div id="output"></div>
        <div>

                @if(Sentinel::getUser()->pic)
                    <img src="{!! url('/').'/uploads/users/'.$user->pic !!}" alt="img"
                         class="img-circle img-responsive "/>

                @elseif(Sentinel::getUser()->gender === "male")
                    <img src="{{ asset('assets/images/authors/avatar3.png') }}" alt="img"
                         class="img-circle img-responsive "/>

                @elseif(Sentinel::getUser()->gender === "female")
                    <img src="{{ asset('assets/images/authors/avatar5.png') }}" alt="img"
                         class="img-circle img-responsive "/>

                @else
                    <img src="{{ asset('assets/images/authors/no_avatar.jpg') }}" alt="img"
                         class="img-circle img-responsive"/>
                @endif
        </div>
        <div class="form-box">
            <form method="POST" name="screen">
                <div class="form">
                    <p class="form-control-static user_name_max">{{Sentinel::getUser()->first_name}}</p>
                    <input type="password" name="user"  id="password" class="form-control" placeholder="Password">
                    <button class="btn btn-info btn-block login" id="index" type="submit">GO</button>
                </div>
            </form>
        </div>
    </div>

</div>
<!-- global js -->
<script src="{{ asset('assets/js/jquery-1.11.1.min.js') }}" type="text/javascript"></script>
<!-- Bootstrap -->
<script src="{{ asset('assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/holder.js') }}"></script>
<!-- end of global js -->
<!-- beginning of page level js-->
<script src="{{ asset('assets/vendors/fort_js/js/fort.js') }}"></script>
{{--<script src="{{ asset('assets/js/pages/lockscreen.js') }}"></script>--}}
<script>Fort.gradient();</script>
<script>
    $(document).ready(function(){
//            var password = $("#password").val();
        /* var password = $("#pwd").val();
         alert(password);*/
        $('button[type="submit"]').click(function(e) {
            e.preventDefault();
            if ( $("#password").val() == "") {
                $("#output").addClass("alert alert-danger").text('Please enter password');
                setTimeout(function() {
                    $("#output").removeClass("alert alert-danger").text('');
                },3500)
            }
            else {
                $.ajax({
                    type: "POST",
                    url: 'lockscreen',
                    data: {password: $("#password").val(), _token: $('meta[name="_token"]').attr('content')},
                    success: function (result) {
                        if (result == 'error') {
                            $("#output").addClass("alert alert-danger").text('You have entered a Wrong Password');
                            setTimeout(function() {
                                $("#output").removeClass("alert alert-danger").text('');
                            },2500)
                        }
                        else {
                            $("#output").addClass("alert alert-success animated fadeInUp user_name_max2").text('Welcome ' + '{!! Sentinel::getUser()->first_name !!}');
                            setTimeout(function(){
                            window.location.href = '../../admin';
                            },1000)
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.responseText);
                    }
                });
            }
            //show avatar
            $(".avatar").css({
                "background-image":  "url('../../assets/img/authors/avatar3.jpg')"
            });
        });
    });
</script>
<!-- end of page level js-->
</body>
</html>